### ISSUE TITLE
In-depth question

### ISSUE THREAD

**Issue by antoineds1** [nazar-pc/ed25519-to-x25519.wasm#1]
The script works well, I try to recode it in rust, I have no trouble finding the same result as you on the public key but the private key gives me more trouble, as there are two distinct functions I was thinking that there must be a manipulation to do or a notion that I do not understand to convert the private key Thank you in advance for the answer.

**Comment by nazar-pc** [comment]
Which two functions are you talking about?

**Comment by antoineds1** [comment]
the function that converts the private key from ed25519 to x25519

**Comment by nazar-pc** [comment]
But there are no 2 functions to convert private keys, there is just one called `convert_private_key`

**Comment by antoineds1** [comment]
is the process for converting the public key and the private key the same?

**Comment by nazar-pc** [comment]
Of course not, why would there be 2 functions in that case?

**Comment by antoineds1** [comment]
When I said the two functions I meant the one to convert the public key and the one to convert the private key, my initial question was to know more about the private key conversion process.

**Comment by nazar-pc** [comment]
There is plenty of information online about this, here is not the best place to ask about it
